# --- General ---
keep-open=yes
save-position-on-quit=yes
autofit-larger=100%x100%

# --- UI / UOSC Requirements ---
border=no

# --- Video / Wayland Optimization ---
# We stick to 'gpu' (OpenGL) to ensure instant startup on Intel/VFIO setups.
# 'gpu-next' (Vulkan) can introduce shader compilation lag on some hardware.
vo=gpu
gpu-context=wayland

# --- Quality ---
scale=spline36
cscale=spline36
dscale=mitchell
correct-downscaling=yes
linear-downscaling=yes
dither-depth=auto

