###############################################################
#  Input devices                                                #
#  https://wiki.hyprland.org/Configuring/Variables/#input       #
###############################################################

input {
    kb_layout = pl
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    mouse_refocus = true

    sensitivity = 0

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        tap-to-click = false
        scroll_factor = 1.0
    }
}

device {
    name = logitech-g-pro--1
	sensitivity = 0
	natural_scroll = true
	accel_profile = flat
}

binds {
    workspace_back_and_forth = true
    allow_workspace_cycles = true
}
