dwindle {
    preserve_split=true
	pseudotile=true
}

general {
    # --- Gaps & Borders ---
    gaps_in = 4                 # Gap between windows
    gaps_out = 8                # Gap between windows and monitor edges
    border_size = 2             # Size of window borders

    # --- Colors ---
    col.active_border = rgb(191724)
    col.inactive_border = rgb(191724)

    # --- Functionality ---
    resize_on_border = true
    layout = dwindle
}

decoration {
    # --- Rounding ---
    rounding = 10
    rounding_power = 2.0

    # --- Opacity ---
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    # --- Dimming ---
    # dim_inactive = true
    # dim_strength = 0.2
    # dim_special = 0.8  # Stronger dimming for special workspace to highlight content

    # --- Shadows ---
    shadow {
        enabled = false
        range = 35
        render_power = 2 #(values betwwen 1 and 4, no higher than 4, cuz invalid)
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 3                
        passes = 1              
        new_optimizations = true
        ignore_opacity = true   
        xray = false           
        noise = 0.0117     
        contrast = 0.9     
        vibrancy = 0.1696
    }
}

# windowrule = suppressevent maximize, class:.*
# windowrule = float, pin, center,size 50% 50% , class: org.pulseaudio.pavucontrol
# windowrule = float, pin, center,size 50% 50% , class: .blueman-manager-wrapped
# windowrule = float, pin, center,size 50% 50% , class: nm-connection-editor
windowrulev2 = suppressevent maximize, class:^(.*)$
windowrulev2 = float, pin, center, size 50% 50%, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = float, pin, center, size 50% 50%, class:^(.blueman-manager-wrapped)$
windowrulev2 = float, pin, center, size 50% 50%, class:^(nm-connection-editor)$
windowrulev2 = opacity 0.9 0.8, class:^(kitty)$

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    middle_click_paste = false
}

# decoration {
#     # rounding = 10
#     rounding = 0
#     blur {
# 	enabled = true
# 	    size = 7
# 	    passes = 4
# 	    ignore_opacity = true
# 	    noise = 0.0117
# 	    contrast = 0.8916
# 	    brightness = 0.8172
# 	    xray = false
# 	    popups = true
#     }
#     shadow {
# 	color = rgba(15, 15, 15, 0.6)
# 	    color_inactive = rgba(15, 15, 15, 0.3)
# 	    offset = 2 2
# 	    range = 11
# 	    render_power = 2
#     }
# }
